clear all;
clc;
import libsvm-3.23.*

load dataset.mat               
load labelset.mat 
%load and process the dataset of label 1
[T1 E1 E2 E3 E4 E5 E6 E7 E8] = csvimport('trainEMGTrue.csv', 'columns', {'timestamp','emg1', 'emg2', 'emg3','emg4','emg5','emg6','emg7','emg8'});
[T2 A1 A2 A3] = csvimport('trainACCTrue.csv', 'columns', {'timestamp','x', 'y', 'z'});
accSetOne = [T2 A1 A2 A3]
trainSetOne = [ T1 E1 E2 E3 E4 E5 E6 E7 E8]
[m,n] = size(trainSetOne);
[m2,n2] = size(accSetOne);
label_t = 1*ones(m,1);
a1=A1(1)
a2=A2(1)
a3=A3(1)
ra = 1
%map the accelerometer data to EMG data
for r = 2 : m
    if T1(r)<=T2(ra)
        a1=vertcat(a1,A1(ra));
        a2=vertcat(a2,A2(ra));
        a3=vertcat(a3,A3(ra));
    else 
        if (ra + 1) <= m2
            ra = ra + 1;
        end
        a1=vertcat(a1,A1(ra));
        a2=vertcat(a2,A2(ra));
        a3=vertcat(a3,A3(ra));
    end
end
a1=normc(a1)
a2=normc(a2)
a3=normc(a3)
trainSetOne = [E1 E2 E3 E4 E5 E6 E7 E8 a1 a2 a3]
%%load and process the dataset of label 2
[ T1 E1 E2 E3 E4 E5 E6 E7 E8] = csvimport('trainEMGFalse.csv', 'columns', {'timestamp','emg1', 'emg2', 'emg3','emg4','emg5','emg6','emg7','emg8'});
[T2 A1 A2 A3] = csvimport('trainACCFalse.csv', 'columns', {'timestamp','x', 'y', 'z'});
trainSetTwo = [ T1 E1 E2 E3 E4 E5 E6 E7 E8]
accSetTwo = [T2 A1 A2 A3]
[m,n] = size(trainSetTwo);
label_f = 0*ones(m,1);
[m2,n2] = size(accSetTwo);
a1=A1(1)
a2=A2(1)
a3=A3(1)
ra = 1
%map the accelerometer data to EMG data
for r = 2 : m
    if T1(r)<=T2(ra)
        a1=vertcat(a1,A1(ra));
        a2=vertcat(a2,A2(ra));
        a3=vertcat(a3,A3(ra));
    else 
        if (ra + 1) <= m2
            ra = ra + 1;
        end
        a1=vertcat(a1,A1(ra));
        a2=vertcat(a2,A2(ra));
        a3=vertcat(a3,A3(ra));
    end
end
a1=normc(a1)
a2=normc(a2)
a3=normc(a3)
trainSetTwo = [E1 E2 E3 E4 E5 E6 E7 E8 a1 a2 a3]

% 
trainSet = vertcat(trainSetOne,trainSetTwo);
lableset = vertcat(label_t,label_f);

%final dataset for Matlab classification learner
dataset = [trainSet lableset];

%Use the trainClassifier generated by matlab classification learner
trainClassifier(dataset)







